### ISSUE TITLE
Specify minimum distance between two CTD stations

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#14]
Since there's a hardcoded tolerance between the CTD and ship location, perhaps specify that multiple CTD stations below this tolerance will lead to problems?

https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L251

**Comment by erikvansebille** [comment]
The same is true for the drifters and Argo deployments:
https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L266

https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L274

**Comment by ammedd** [comment]
It doesn't apply for the argos and floats, because thats caught with the while loop and break. There I expect (and tested with) several within the tolerance.
For CTDs you're right...
It's a bit complex because the pyproj.Geod.inv function that computes the "travel route" doesn't work if the points are too close (<0.01) together. I'll add an else there that should solve this. Ask me to explain/discuss in person if you want.
